import { makeStyles } from "@mui/styles";
export const MostPopularInYourCityStyle = makeStyles({
  mostPopularSection: {
    marginTop: "6%",
    "& .most-popular-section-tagline": {
      fontSize: "15px",
      fontFamily: "axiforma-reg",
      lineHeight: "1",
      marginBottom: "6%",
    },
    "& h1": {
      fontFamily: "axiforma-bold",
      lineHeight: "1",
    },
    "& .icon-white": {
      color: "#ffffff",
    },
    "& .add-more-btn-box": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    "& .add-more-btn-box .add-icon": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "40px",
      height: "40px",
      backgroundColor: "#ABE236",
      borderRadius: "100px",
    },
    "& .most-popular-card": {
      width: "100%",
      height: "235px",
      backgroundColor: "#ffffff",
      filter: "drop-shadow(10px 10px 12px rgba(0, 0, 0, 0.15))",
      borderRadius: "15px",
      marginBottom: "5%",
      zIndex: 0,
      "& span": {
        lineHeight: "1",
      },
    },
    "& .most-popular-card .most-popular-card-img-box": {
      width: "100%",
      height: "184px",
      borderTopLeftRadius: "15px",
      borderTopRightRadius: "15px",
      position: "relative",
      zIndex: 1,
    },
    "& .most-popular-card .most-popular-card-img-box .card-img": {
      height: "100%",
      width: "100%",
      objectFit: "cover",
      objectPosition: "center",
      overflow: "hidden",
      borderTopLeftRadius: "15px",
      borderTopRightRadius: "15px",
    },
    "& .most-popular-card .most-popular-card-title": {
      color: "#000929",
      fontFamily: "axiforma-bold",
      textAlign: "center",
      height: "51px",
      lineHeight: "51px",
    },
    "& .most-popular-card-hover::before": {
      position: "absolute !important",
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      content: '""',
      width: "100%",
      height: "100%",
      borderTopLeftRadius: "15px",
      borderTopRightRadius: "15px",
    },
    "& .most-popular-card .most-popular-hover-icon": {
      position: "absolute",
      top: "45%",
      left: "50%",
      width: "75px",
      height: "99px",
      transform: "translate(-50%, -50%)",
      zIndex: 2,
      "& img": {
        border: "3px solid #ABE236",
        borderRadius: "50px",
      },
    },
    "& .most-popular-card .most-popular-card-text-hover": {
      borderBottomLeftRadius: "15px",
      borderBottomRightRadius: "15px",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      height: "51px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-around",
    },
    "& .most-popular-card-text-hover": {},
    "& .most-popular-card-text-hover .time-duration": {
      fontSize: "14px",
      color: "#ffffff",
      fontWeight: "bold",
      marginRight: "10px",
      minWidth: "max-content",
    },
    "& .most-popular-card-text-hover .like": {
      fontWeight: "bold !important",
      color: "#ffffff",
      minWidth: "max-content",
    },
    "& .most-popular-card-text-hover .percentage": {
      fontSize: "14px",
      color: "#ffffff",
      fontWeight: "bold",
      paddingLeft: "8px",
      minWidth: "max-content",
    },
    "& .most-popular-card-text-hover .views": {
      fontSize: "14px",
      paddingLeft: "15px",
      color: "#ffffff",
      minWidth: "max-content",
    },
    "& .most-popular-card-on-mobile": {
      width: "100%",
      height: "138px",
      backgroundColor: "#ffffff",
      filter: "drop-shadow(10px 10px 12px rgba(0, 0, 0, 0.15))",
      borderRadius: "15px",
      "& p": {
        lineHeight: "1",
      },
    },
    "& .most-popular-card-on-mobile .most-popular-card-img-box": {
      width: "100%",
      height: "100%",
      borderRadius: "15px",
      position: "relative",
    },
    "& .most-popular-card-on-mobile .most-popular-card-img-box .card-img": {
      height: "100%",
      width: "100%",
      objectFit: "cover",
      objectPosition: "center",
      overflow: "hidden",
      borderRadius: "15px",
    },
    "& .most-popular-card-text-on-mobile": {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "10px 5px",
    },
    "& .most-popular-card-on-mobile .most-popular-card-title": {
      color: "#000929",
      fontWeight: "bold",
      textAlign: "center",
    },
    "& .most-popular-card-on-mobile .most-popular-card-hover::before": {
      position: "absolute !important",
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      content: '""',
      width: "100%",
      height: "100%",
      borderRadius: "15px",
    },
    "& .most-popular-card-on-mobile .most-popular-center-text": {
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
    "& .most-popular-card-on-mobile .most-popular-center-text span": {
      color: "#ffffff",
      fontSize: "20px",
    },
    "& .most-popular-card-text-on-mobile .time-duration": {
      fontSize: "14px",
      color: "#5C5C5C",
      fontWeight: "bold",
      marginRight: "10px",
    },
    "& .most-popular-card-text-on-mobile .like": {
      fontWeight: "bold !important",
      color: "#5C5C5C",
    },
    "& .most-popular-card-text-on-mobile .percentage": {
      fontSize: "14px",
      color: "#5C5C5C",
      fontWeight: "bold",
      paddingLeft: "8px",
    },
    "& .most-popular-card-text-on-mobile .views": {
      fontSize: "14px",
      paddingLeft: "15px",
      color: "#5C5C5C",
    },
    "& .most-popular-card-on-mobile .icon-gray": {
      color: "#5C5C5C !important",
      fontWeight: "bold !important",
    },
    "& .d-none": {
      display: "none !important",
    },
    "& .text-white": {
      color: "#ffffff",
    },
    "& .most-popular-hover-title": {
      position: "absolute",
      top: "78%",
      left: "50%",
      fontSize: "16px",
      color: "#ffffff",
      transform: "translate(-50%,-50%)",
      fontFamily: "axiforma-bold",
    },
  },
});
